### ISSUE TITLE
Few shot is incomplete

### ISSUE THREAD

**Issue by einarbmag** [explosion/prodigy-openai-recipes#65]
I was trying to get few-shot to work by flagging examples during labelling, but it just wasn't working. Then I noticed that PromptExample.from_prodigy just isn't implemented yet... Did you perhaps forget to commit that file?

**Comment by einarbmag** [comment]
Ah. I see from a comment on your closed issue that this will be included with the next release of Prodigy, hopefully this will be fixed there?

**Comment by koaning** [comment]
I just checked the internal version and it does indeed have `from_prodigy` implemented within the `update()` callback. While I can't promise much, we are contemplating an alpha release of a new Prodigy version soon. You can keep an eye on our support forum where we'll announce it.

**Comment by koaning** [comment]
The recipes in this repository have since moved to [Prodigy](https://prodi.gy/) and are being maintained there. They will soon even get an upgrade with the advent of [spacy-llm](https://github.com/explosion/spacy-llm) support, which features better prompts and multiple LLM providers. That is why we've opted to archive this repo, which is also why I'm closing all the issues.

You can learn more by checking out the [large language models section](https://prodi.gy/docs/large-language-models) on the docs.
